version: "3.7"

services:
  api:
    build: .
    ports:
      - "8383:80"
    env_file: "config.env"
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crudgo
    ports:
      - 127.0.0.1:7599:5432
    volumes:
      - .data/crudgo:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - .data/rabbitmq/data/:/var/lib/rabbitmq
      - .data/rabbitmq/log/:/var/log/rabbitmq
