version: "3.7"

services:
  api:
    build: .
    ports:
      - "8765:80"
    env_file: "config.env"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crudgo
    ports:
      - 127.0.0.1:7599:5432
    volumes:
      - .data/crudgo:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - .data/rabbitmq/data/:/var/lib/rabbitmq
      - .data/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 5s
      retries: 3
      start_period: 30s
